

$(eval $(call BuildPackage,agocontrol-device-enocean3))
$(eval $(call BuildPackage,agocontrol-device-blinkm))
$(eval $(call BuildPackage,agocontrol-device-chromoflex))
$(eval $(call BuildPackage,agocontrol-device-firmata))
$(eval $(call BuildPackage,agocontrol-device-i2c))
$(eval $(call BuildPackage,agocontrol-device-irtrans_ethernet))
$(eval $(call BuildPackage,agocontrol-device-kwikwai))
$(eval $(call BuildPackage,agocontrol-device-mediaproxy))
$(eval $(call BuildPackage,agocontrol-device-rain8net))
$(eval $(call BuildPackage,agocontrol-device-zwave))
$(eval $(call BuildPackage,agocontrol-device-1wire))
$(eval $(call BuildPackage,agocontrol-device-syslog))
$(eval $(call BuildPackage,agocontrol-device-enigma2))
$(eval $(call BuildPackage,agocontrol-device-asterisk))
$(eval $(call BuildPackage,agocontrol-device-agoapc))
$(eval $(call BuildPackage,agocontrol-device-agojointspace))
$(eval $(call BuildPackage,agocontrol-device-raspiGPIO))
$(eval $(call BuildPackage,agocontrol-device-raspi1wGPIO))
$(eval $(call BuildPackage,agocontrol-device-raspiMCP3xxxGPIO))
$(eval $(call BuildPackage,agocontrol-device-gc100))
$(eval $(call BuildPackage,agocontrol-device-onkyo))
$(eval $(call BuildPackage,agocontrol-device-x10))
$(eval $(call BuildPackage,agocontrol-device-webcam))
$(eval $(call BuildPackage,agocontrol-device-temperatur.nu))
$(eval $(call BuildPackage,agocontrol-device-wake_on_lan))
$(eval $(call BuildPackage,agocontrol-device-squeezebox))
$(eval $(call BuildPackage,agocontrol-device-alert))
$(eval $(call BuildPackage,agocontrol-device-ipx800))
$(eval $(call BuildPackage,agocontrol-device-raspiCamera))
$(eval $(call BuildPackage,agocontrol-device-scheduler))
$(eval $(call BuildPackage,agocontrol-device-knx))
$(eval $(call BuildPackage,agocontrol-device-agodmx))


