include devices/enocean.mk
include devices/blinkm.mk
include devices/chromoflex.mk
include devices/firmata.mk
include devices/i2c.mk
include devices/irtrans_ethernet.mk
include devices/kwikwai.mk
include devices/mediaproxy.mk
include devices/rain8net.mk
include devices/zwave.mk
include devices/1wire.mk
include devices/syslog.mk
include devices/enigma2.mk
include devices/asterisk.mk
include devices/agoapc.mk
include devices/agojointspace.mk
include devices/raspiGPIO.mk
include devices/raspi1wGPIO.mk
include devices/raspiMCP3xxxGPIO.mk
include devices/gc100.mk
include devices/onkyo.mk
include devices/x10.mk
include devices/webcam.mk
include devices/temperatur.nu.mk
include devices/wake_on_lan.mk
include devices/squeezebox.mk
include devices/alert.mk
include devices/ipx800.mk
include devices/raspiCamera.mk
include devices/scheduler.mk
include devices/knx.mk
include devices/agodmx.mk
